services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarasov_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tarasov_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static_volume: