# Generated by Django 6.0.3 on 2026-04-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('pc_type', models.CharField(choices=[('pc_weekday', 'PC (будни)'), ('pc_weekend', 'PC (выходные)'), ('ps5_one', 'PS5 (один)'), ('ps5_two', 'PS5 (два)')], max_length=20, verbose_name='Тип места')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('hours', models.PositiveIntegerField(default=1, verbose_name='Количество часов')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('booking_number', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Номер бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
