# Generated by Django 6.0.3 on 2026-04-01 18:56

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='access_expires_at',
            field=models.DateTimeField(default=booking.models.booking_token_expiry),
        ),
        migrations.AddField(
            model_name='booking',
            name='access_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pc_type',
            field=models.CharField(choices=[('pc_weekday', 'PC (будни)'), ('pc_weekend', 'PC (выходные)'), ('ps5_one', 'PS5 (1 игрок)'), ('ps5_two', 'PS5 (2 игрока)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
