# Generated by Django 6.0.3 on 2026-04-01 19:18

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_options_alter_booking_access_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение поддержки', 'verbose_name_plural': 'Сообщения поддержки'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Тикет поддержки', 'verbose_name_plural': 'Тикеты поддержки'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='access_expires_at',
            field=models.DateTimeField(default=booking.models.booking_token_expiry, verbose_name='Доступ действует до'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='access_token',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(max_length=8, unique=True, verbose_name='Номер бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hours',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pc_type',
            field=models.CharField(choices=[('pc_weekday', 'PC (будни)'), ('pc_weekend', 'PC (выходные)'), ('ps5_one', 'PS5 (1 игрок)'), ('ps5_two', 'PS5 (2 игрока)')], max_length=20, verbose_name='Тип места'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_at',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='author_type',
            field=models.CharField(choices=[('user', 'Клиент'), ('admin', 'Администратор')], max_length=20, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='booking.supportticket', verbose_name='Тикет'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket', to='booking.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('answered', 'Есть ответ'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
