# Generated by Django 6.0.3 on 2026-04-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options_alter_supportmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='author_type',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], max_length=20, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус'),
        ),
    ]
